---
# application.yml
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rashmitk/spring_cloud_config_repo.git
          searchPaths: ConfigurationRepo
server:
  port: 8888