spring:
  profiles: es3
server:
  port: 8503  
eureka:
  instance:
    hostname: eurekaserver-3 
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eurekaserver-1:8501,http://eurekaserver-2:8502    
